apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: patches/migrate-job.yaml
    target:
      group: batch
      kind: Job
      name: migrate
      namespace: stock-analysis
      version: v1
  - path: patches/api-deployment.yaml
    target:
      group: apps
      kind: Deployment
      name: api
      namespace: stock-analysis
      version: v1
  - path: patches/worker-deployment.yaml
    target:
      group: apps
      kind: Deployment
      name: worker
      namespace: stock-analysis
      version: v1
  - path: patches/web-deployment.yaml
    target:
      group: apps
      kind: Deployment
      name: web
      namespace: stock-analysis
      version: v1
  - path: patches/ingress-dev.yaml
    target:
      group: networking.k8s.io
      kind: Ingress
      name: app-ingress
      namespace: stock-analysis
      version: v1
