apiVersion: v1
kind: ConfigMap
metadata:
  name: app
data:
  DATABASE_HOST: "postgres"
  DATABASE_PORT: "5432"
  CONFIG_DIR: "configs/api/cninfo"
  RULE_FILE_PATH: "configs/rules/scoring_rules_sample.yaml"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
  BACKEND_HOST: "0.0.0.0"
  BACKEND_PORT: "8000"
  WORKER_LOG_LEVEL: "INFO"
  BATCH_SIZE: "2"
  MAX_CONCURRENT_TASKS: "5"
  VLLM_SERVER_HOST: "vllm"
  VLLM_SERVER_PORT: "8000"
  VLLM_MODEL: "Qwen/Qwen3-0.6B"
  VLLM_MAX_MODEL_LENGTH: "1024"
  VLLM_MAX_NUM_SEQUENCES: "2"
  GPU_MEMORY_UTILIZATION: "0.8"
  VLLM_TEMPERATURE: "0.7"
  FRONTEND_HOST: "0.0.0.0"
  FRONTEND_PORT: "3000"
