api:
  id: lift_ban
  name: 限售解禁
  request:
    method: GET
    url: http://www.cninfo.com.cn/data20/stockholderCapital/getLiftBan
    params:
      stock_code:
        label: scode
        type: string
        name: 证券代码
response:
  label: response
  type: object
  path:
    label: path
    type: string
    value: /stockholderCapital/getLiftBan
  code:
    label: code
    type: integer
    value: 200
  data:
    label: data
    type: object
    total:
      label: total
      type: integer
    count:
      label: count
      type: integer
    result_msg:
      label: resultMsg
      type: string
      value: success
    result_code:
      label: resultCode
      type: string
      value: "200"
    records:
      label: records
      type: array
      items:
        label: items
        type: object
        stock_code:
          label: SECCODE
          type: string
          name: 证券代码
        stock_name:
          label: SECNAME
          type: string
          name: 证券简称
        announce_date:
          label: DECLAREDATE
          type: string
          name: 公告日期
        actual_unlock_date:
          label: F003D
          type: string
          name: 实际解除限售日期
        unlock_shares:
          label: F004N
          type: integer
          name: 实际解除限售数量
        unlock_ratio:
          label: F005N
          type: number
          name: 实际解除限售比例
        related_amount:
          label: F008N
          type: integer
          name: 解禁相关数量
    index_records:
      label: indexRecords
      type: "null"
  params:
    label: params
    type: object
    stock_code_request:
      label: stockCodeRequest
      type: object
      stock_code:
        label: scode
        type: string
