api:
  id: margin_trading
  name: 融资融券
  request:
    method: GET
    url: http://www.cninfo.com.cn/data20/tradeInformation/getMarginTrading
    params:
      stock_code:
        label: scode
        type: string
        name: 证券代码
response:
  label: response
  type: object
  path:
    label: path
    type: string
    value: /tradeInformation/getMarginTrading
  code:
    label: code
    type: integer
    value: 200
  data:
    label: data
    type: object
    total:
      label: total
      type: integer
    count:
      label: count
      type: integer
    result_msg:
      label: resultMsg
      type: string
      value: success
    result_code:
      label: resultCode
      type: string
      value: '200'
    records:
      label: records
      type: array
      items:
        label: items
        type: object
        stock_name:
          label: SECNAME
          type: string
          name: 证券简称
        stock_code:
          label: SECCODE
          type: string
          name: 证券代码
        securities_lending_balance_shares:
          label: F004N
          type: number
          name: 本日融券余量
        financing_buy_amount:
          label: F002N
          type: number
          name: 本日融资买入额
        financing_balance:
          label: F001N
          type: number
          name: 本日融资余额
        securities_lending_balance_amount:
          label: F008N
          type: number
          name: 融券余额金额
        trade_date:
          label: TRADEDATE
          type: string
          name: 交易日期
        securities_lending_sell_volume:
          label: F006N
          type: integer
          name: 本日融券卖出量
        total_margin_balance:
          label: F009N
          type: number
          name: 融资融券余额
    index_records:
      label: indexRecords
      type: 'null'
  params:
    label: params
    type: object
    stock_code_request:
      label: stockCodeRequest
      type: object
      stock_code:
        label: scode
        type: string
