api:
  id: stockholeder_inc_dec_detail
  name: 股东增减持
  request:
    method: GET
    url: http://www.cninfo.com.cn/data20/tradeInformation/getStockholederIncDecDetail
    params:
      stock_code:
        label: scode
        type: string
        name: 证券代码
response:
  label: response
  type: object
  path:
    label: path
    type: string
    value: /tradeInformation/getStockholederIncDecDetail
  code:
    label: code
    type: integer
    value: 200
  data:
    label: data
    type: object
    total:
      label: total
      type: integer
    count:
      label: count
      type: integer
    result_msg:
      label: resultMsg
      type: string
      value: success
    result_code:
      label: resultCode
      type: string
      value: "200"
    records:
      label: records
      type: array
      items:
        label: items
        type: object
        stock_code:
          label: SECCODE
          type: string
          name: 证券代码
        stock_name:
          label: SECNAME
          type: string
          name: 证券简称
        declare_date:
          label: DECLAREDATE
          type: string
          name: 公告日期
        vary_date:
          label: varydate
          type: string
          name: 增/减持日期
        direction:
          label: F001C
          type: string
          name: 增减持方向
        share_change_ratio:
          label: F005N
          type: number
          name: 增/减持比例
        share_change_amount:
          label: F004N
          type: integer
          name: 增/减持数量
        price_range:
          label: F007V
          type: string
          name: 交易价格情况
        holder_name:
          label: F002V
          type: string
          name: 股东名称
    index_records:
      label: indexRecords
      type: "null"
  params:
    label: params
    type: object
    stock_code_request:
      label: stockCodeRequest
      type: object
      stock_code:
        label: scode
        type: string
